services:
  - type: web
    name: valolink-web
    env: node
    repo: https://github.com/huchialun9-ctrl/ValoLink.gg.git
    buildCommand: npm run build:web
    startCommand: npx prisma@5.22.0 db push --schema=packages/db/prisma/schema.prisma --accept-data-loss && npm run start --workspace=apps/web
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_LIVEKIT_URL
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: DISCORD_TOKEN
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: DATABASE_URL
        sync: false
